### ISSUE TITLE
Easy way to check for group membership?

### ISSUE THREAD

**Issue by CurtTilmes** [jonathanstowe/Unix-Groups#1]
What's the easiest idiom to check if `$user` is a member of `$group`?

**Comment by jonathanstowe** [comment]
Gosh, I haven't looked at this for three years as I made it to support another module in lieu of anything else :)

But the easiest way to doing that as it stands is something like : 

```
perl6 -Ilib -MUnix::Groups -e 'say so Unix::Groups.new.groups-for-user("jonathan").grep("liquidsoap")
```

Though substituting the appropriate user and group.

The groups file is read once so if you want to check a few users you'd just make one instance,

**Comment by CurtTilmes** [comment]
Thanks!
